const natural = require('natural');
const Report = require('../models/Report');
const User = require('../models/User');
const Donation = require('../models/Donation');

// Initialize natural Sentiment Analyzer
// PorterStemmer is used to extract word roots
const Analyzer = natural.SentimentAnalyzer;
const stemmer = natural.PorterStemmer;
const analyzer = new Analyzer("English", stemmer, "afinn");

/**
 * Calculates sentiment score using the AFINN vocabulary.
 * Returns a score where < 0 is negative, > 0 is positive.
 */
function getSentimentScore(text) {
  if (!text || typeof text !== 'string') return 0;
  try {
    const tokenizer = new natural.WordTokenizer();
    const tokens = tokenizer.tokenize(text.toLowerCase());
    if (tokens.length === 0) return 0;
    
    // getSentiment returns a float (typically between -5 and 5 divided by word count)
    return analyzer.getSentiment(tokens);
  } catch (err) {
    console.warn("⚠️ Sentiment Analyzer warning:", err.message);
    return 0;
  }
}

/**
 * Evaluates fraud score using multiple factors:
 * - Review sentiment score
 * - Target user rating history (avgRating)
 * - Abuse reports count (flagCount / reports filed in DB)
 * - Count of rejected/needs_review donations
 * - Low safety scores from AI scans
 */
async function analyzeFraudRisk(targetUserId, reviewerId, donationId, reviewComment, reviewRating) {
  try {
    const targetUser = await User.findById(targetUserId);
    if (!targetUser) return { fraudScore: 0, riskLevel: 'low' };

    let score = 0;

    // 1. Review Rating Factor (low ratings indicate bad exchanges)
    if (reviewRating <= 1) score += 35;
    else if (reviewRating <= 2) score += 25;
    else if (reviewRating <= 3) score += 15;

    // 2. Review Sentiment NLP (analyzing feedback text for warning signs)
    const sentiment = getSentimentScore(reviewComment);
    if (sentiment < -0.5) {
      score += 25; // Highly negative sentiment
    } else if (sentiment < 0) {
      score += 15; // Slightly negative sentiment
    }

    // 3. User History (Average rating on SpareShare)
    if (targetUser.avgRating !== null && targetUser.avgRating !== undefined) {
      if (targetUser.avgRating < 2.0) score += 30;
      else if (targetUser.avgRating < 3.5) score += 15;
    }

    // 4. Historical reports count
    const historicalReports = await Report.countDocuments({ 
      donationId: { $in: await Donation.find({ $or: [{ donorId: targetUserId }, { receiverId: targetUserId }] }).select('_id') }
    });
    score += Math.min(historicalReports * 15, 30); // Cap historical reports factor at 30

    // 5. Count of flagged/needs_review items from AI
    const lowAiScoreDonations = await Donation.countDocuments({
      $or: [{ donorId: targetUserId }, { receiverId: targetUserId }],
      status: { $in: ['needs_review', 'rejected'] }
    });
    score += Math.min(lowAiScoreDonations * 10, 20); // Cap at 20

    // 6. Suspicious patterns (e.g. key words in comment related to fraud/selling/theft/hoarding/fake NGOs)
    const suspiciousKeywords = [
      'sell', 'sold', 'charge', 'money', 'fake', 'stole', 'stolen', 'expired', 
      'bad food', 'harm', 'threat', 'ruined', 'dirty', 'resell', 'hoarding', 
      'hoard', 'commercial', 'not ngo', 'business', 'fake profile', 'never arrived', 
      'no show', 'absent', 'demanded'
    ];
    if (reviewComment) {
      const lowerComment = reviewComment.toLowerCase();
      const matchedSuspicious = suspiciousKeywords.filter(kw => lowerComment.includes(kw));
      score += matchedSuspicious.length * 10;
    }

    // 7. Receiver-specific check: if target user is a receiver and has claimed many donations with low average rating
    if (targetUser.role === 'receiver') {
      const totalClaims = await Donation.countDocuments({ 
        $or: [{ receiverId: targetUserId }, { claimedBy: targetUserId }], 
        status: 'completed' 
      });
      if (totalClaims > 5 && targetUser.avgRating && targetUser.avgRating < 3.5) {
        score += 20; // High volume with low trust indicates possible hoarding/fraud
      }
    }

    // Normalize final score to a maximum of 100
    const finalScore = Math.min(Math.round(score), 100);
    
    let riskLevel = 'low';
    if (finalScore >= 75) {
      riskLevel = 'high';
    } else if (finalScore >= 45) {
      riskLevel = 'medium';
    }

    // Auto-generate report in database if risk level is medium or high
    if (riskLevel === 'high' || riskLevel === 'medium') {
      const autoReport = new Report({
        donationId: donationId,
        reporterId: reviewerId,
        reason: riskLevel === 'high' 
          ? `High Risk Automated AI ${targetUser.role === 'receiver' ? 'Receiver' : 'Donor'} Fraud Flag` 
          : `Suspicious ${targetUser.role === 'receiver' ? 'Receiver' : 'Donor'} Exchange Feedback`,
        details: `Automated report generated by AI NLP Analyzer. Role being reviewed: ${targetUser.role.toUpperCase()}. Sentiment polarity: ${sentiment.toFixed(2)}. Computed Fraud Score: ${finalScore}%. Comment: "${reviewComment || 'No comment provided'}"`,
        status: 'pending',
        adminNote: `Generated using natural AFINN Sentiment Analyzer & Multi-factor heuristics. Target user: ${targetUser.name} (${targetUser.role}). Fraud rating: ${finalScore}% risk.`
      });
      await autoReport.save();

      // Automatically increment user flagCount
      targetUser.flagCount = (targetUser.flagCount || 0) + 1;
      if (targetUser.flagCount >= 3) {
        targetUser.isBlocked = true;
      }
      await targetUser.save();
      
      console.log(`🚨 [FRAUD ENGINE] Auto-created fraud report for ${targetUser.role} ${targetUserId} with risk: ${riskLevel} (${finalScore}%)`);
    }

    return {
      fraudScore: finalScore,
      riskLevel,
      sentimentPolarity: sentiment
    };

  } catch (err) {
    console.error('❌ Fraud AI Engine Error:', err.message);
    return { fraudScore: 0, riskLevel: 'low', error: err.message };
  }
}

module.exports = {
  getSentimentScore,
  analyzeFraudRisk
};
